# Generated by Django 4.2.13 on 2024-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
