# Generated by Django 4.2.13 on 2024-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_password_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="baseUrl",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="clintId",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
