# Generated by Django 4.2.13 on 2024-06-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_organization_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="baseUrl",
            new_name="base_url",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="clintId",
            new_name="clint_id",
        ),
    ]
