# Generated by Django 4.2.13 on 2024-06-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_branch_available_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "branch"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
