# Generated by Django 4.2.13 on 2024-06-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_branch_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
