# Generated by Django 4.2.13 on 2024-06-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_branch_client_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="client_id",
            new_name="member_number",
        ),
    ]
