# Generated by Django 4.2.13 on 2024-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_client_id_branch_member_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="access_accounts",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
